
- hosts: ha_master

  gather_facts: no
  vars:
    https: True
    intf_inconsistency: []
  tasks:

  - name: Get Interface information
    delegate_to: localhost
    fortiosconfig:
      config: "system interface"
      action: "get"
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: "{{ https }}"
    register: interface_info

  - debug: var=interface_info

  - name: "Check if interfaces are configured"
    set_fact:
      intf_inconsistency: "{{ intf_inconsistency + [ inventory_hostname + ': ' + item.name + ' has unexpected IP of '+ item.ip | string + ip[item.name].address | ipaddr('address') | string + item.ip | ipv4 | string ] }}"
    when:
      - ip[item.name] is defined
      - (ip[item.name].address | ipaddr("address") | string + " " + ip[item.name].address | ipaddr("netmask") | string) != item.ip
      - not (ip[item.name].address == "0.0.0.0/0" and item.ip == "0.0.0.0 0.0.0.0") 
    loop: "{{ interface_info.meta.results }}"

  - name: Analyze and print result
    debug:
       msg: "{{ 'Interface config ok' if (intf_inconsistency | length) == 0 else intf_inconsistency}}"
