
- hosts: ha_master

  gather_facts: no
  tasks:

  - name: User radclient to assign service via rsso
    delegate_to: localhost
    shell: "echo \"
          Acct-Status-Type=Start,
          NAS-IP-Address=10.10.10.10,
          Calling-Station-Id={{ user }},
          Framed-IP-Address={{ hostvars['test_client'].pub_ip }},
          Framed-IPv6-Address={{ hostvars['test_client'].pub_ip6 }},
          Filter-Id={{ filterid }}
          \" | radclient -x {{ host }} acct {{ radius_accounting.secret }}"

  - name: Get user firewall auth information
    delegate_to: localhost
    fortiosconfig:
      config: "user firewall"
      action: "monitor"
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: True
      ssl_verify: False
    register: user_fw_auth_info

  - debug:
      msg: "{{ user_fw_auth_info }}"

  - set_fact:
      qry: "[?username=='{{ user|upper }}']"

  - set_fact:
      userinfo: "{{ user_fw_auth_info.meta.results | json_query(qry) }}"
    with_items: "{{ groups['prod'] }}"

  - set_fact:
      user_info_msg: "{{ user_info_msg | default([]) + ['User ' + user + ' auth from ' + item.ipaddr + ', usergroup ' + item.usergroup | string ] }}"
    with_items: "{{ userinfo }}"
    when: userinfo | length != 0

  - debug:
      msg: "{{ user_info_msg }}"
    when: userinfo | length != 0

  - debug:
      msg: "No auth session found for user {{ user }}"
    when: userinfo | length == 0
