
- hosts: ha_master

  gather_facts: no
  tasks:

  - name: Bring up interface
    delegate_to: localhost
    fortiosconfig:
      action: "put"
      host: "{{ host }}"
      username: "{{  username }}"
      password: "{{ password }}"
      vdom:  "{{  vdom }}"
      config: "system interface"
      config_parameters:
        name: "{{ port }}"
        json:
          name: "{{ port }}"
          status: "up"
